tests/ts_calibrate: add missing headers
The open(2) system call requires sys/types.h and sys/stat.h. Fix the following
build failure under uClibc-ng:

ts_calibrate.c: In function ‘main’:
ts_calibrate.c:248:19: error: ‘S_IRUSR’ undeclared (first use in this function)
                   S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);
                   ^